### ISSUE TITLE
browser compatability; custom word list

### ISSUE THREAD

**Issue by brumm** [capnajax/ideal-password#10]
Hey!

I'd love to use this in the browser, but the filesystem access presents a problem. Would you be interested in making the wordlist configurable?

This way I could use a list more specific to my region, and we could remove the file system access, making it compatible for use in the browser.

I'd be interested in adding this feature if you are :)

**Comment by capnajax** [comment]
tl;dr your help are absolutely welcome.

So far I have only been working and testing on Node.js, with this operating as a service, but I can see how it would be useful to put that entirely in the client side.

Unfortunately I do almost no browser-side work, so I could use your expertise in this. For example, how does test automation work on client-side code, and am I using any ES6 features that might not be commonly available on browsers?

Thanks for your help in this!

**Comment by dchambers** [comment]
Also love this library! I looked at the all the alternatives last night and this was the only one I played with that felt genuinely intuitive regarding how the entropy grew or shrank as I changed the password. Also the only one that has educational potential due to the provision of the token-set names that could be displayed to the user as badges as they type.

I've created #11 so that I could make use this, if you can take a look when you get a chance please.

**Comment by capnajax** [comment]
Hi @brumm regarding web usability, @dchambers has you covered! He added web usability. 

Regarding word list customizability, In 2.2 there's a new feature to allow the addition of custom words beyond the list provided. My apologies, these were not merged into the master branch until today.

Version 2.3 is released today on npm. Thank you for your great feedback!

**Comment by brumm** [comment]
Amazing! Sorry to let you down, I had not found the time to do it yet :) Thanks @dchambers!
